/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as BriefingTokenRouteImport } from './routes/briefing.$token'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as BriefingTokenEnviadoRouteImport } from './routes/briefing.$token.enviado'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingTokenRoute = BriefingTokenRouteImport.update({
  id: '/briefing/$token',
  path: '/briefing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingTokenEnviadoRoute = BriefingTokenEnviadoRouteImport.update({
  id: '/enviado',
  path: '/enviado',
  getParentRoute: () => BriefingTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/admin/$id': typeof AdminIdRoute
  '/briefing/$token': typeof BriefingTokenRouteWithChildren
  '/editor/$id': typeof EditorIdRoute
  '/briefing/$token/enviado': typeof BriefingTokenEnviadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/admin/$id': typeof AdminIdRoute
  '/briefing/$token': typeof BriefingTokenRouteWithChildren
  '/editor/$id': typeof EditorIdRoute
  '/briefing/$token/enviado': typeof BriefingTokenEnviadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/admin/$id': typeof AdminIdRoute
  '/briefing/$token': typeof BriefingTokenRouteWithChildren
  '/editor/$id': typeof EditorIdRoute
  '/briefing/$token/enviado': typeof BriefingTokenEnviadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/admin/$id'
    | '/briefing/$token'
    | '/editor/$id'
    | '/briefing/$token/enviado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/admin/$id'
    | '/briefing/$token'
    | '/editor/$id'
    | '/briefing/$token/enviado'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/admin/$id'
    | '/briefing/$token'
    | '/editor/$id'
    | '/briefing/$token/enviado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  AdminIdRoute: typeof AdminIdRoute
  BriefingTokenRoute: typeof BriefingTokenRouteWithChildren
  EditorIdRoute: typeof EditorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$token': {
      id: '/briefing/$token'
      path: '/briefing/$token'
      fullPath: '/briefing/$token'
      preLoaderRoute: typeof BriefingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$token/enviado': {
      id: '/briefing/$token/enviado'
      path: '/enviado'
      fullPath: '/briefing/$token/enviado'
      preLoaderRoute: typeof BriefingTokenEnviadoRouteImport
      parentRoute: typeof BriefingTokenRoute
    }
  }
}

interface BriefingTokenRouteChildren {
  BriefingTokenEnviadoRoute: typeof BriefingTokenEnviadoRoute
}

const BriefingTokenRouteChildren: BriefingTokenRouteChildren = {
  BriefingTokenEnviadoRoute: BriefingTokenEnviadoRoute,
}

const BriefingTokenRouteWithChildren = BriefingTokenRoute._addFileChildren(
  BriefingTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  AdminIdRoute: AdminIdRoute,
  BriefingTokenRoute: BriefingTokenRouteWithChildren,
  EditorIdRoute: EditorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
